Repository 2024-SummerBootcamp-Team/backend, pull requests merged in 2024-07, with the labels that each got.

#8 [feat] aws 설정 - SecretManager, S3 Upload, unitTest
  app/config/aws/s3Client.py
  app/config/aws/secret.py
  app/database/session.py
  app/test/unit/uploadUnitTest.py
Labels: enhancement

#33 [set/#16] Secret Manager 값을 env로 환경설정을 가져올 수 있도록 수정
  app/config/aws/secret.py
  app/config/config.py
  app/config/envSetting.py
  app/database/session.py
  app/main.py
Labels: ⚙ Setting, 🔨 Refactor

#35 [feat/#11] 발췌 이미지 생성 기능 추가
  app/config/aws/s3Client.py
  app/routers/images.py
  app/schemas/image.py
  app/services/bubble_service.py
  app/services/image_service.py
Labels: ✨ Feature

#34 [feat/#15] 임시 TTS 생성 API 구현 및 CORS 설정
  .gitignore
  app/config/elevenlabs/text_to_speech_file.py
  app/config/elevenlabs/text_to_speech_stream.py
  app/main.py
  app/requirements.txt
  app/routers/index.html
  app/routers/voices.py
  app/schemas/voice.py
  app/services/voice_service.py
Labels: ✨ Feature

#52 [Feat/#24] GPT 스트림 음성 완 - 비동기 처리 완료
  app/config/elevenlabs/text_to_speech_stream.py
  app/routers/chats.py
  app/services/bubble_service.py
Labels: ✨ Feature, 🔨 Refactor

#53 [feat/#23] 모니터링 그라파나 프로메테우스 cadvisor추가 긍정적 검토바람!!
  app/main.py
  app/requirements.txt
  app/routers/chats.py
  app/services/chat_service.py
  docker-compose.yml
  prometheus.yml
Labels: ✨ Feature

#59 [refactor/#26] API docs 수정 및 사용하지 않는 코드 삭제
  app/main.py
  app/routers/api.py
  app/routers/chats.py
  app/routers/images.py
  app/routers/tests.py
  app/routers/voices.py
Labels: 🔨 Refactor

#64 [feat/#18] 랭체인 프롬프트
  app/config/langChain/chatMessageHistory.py
  app/config/langChain/langChainSetting.py
  app/main.py
  app/requirements.txt
  app/services/bubble_service.py
  app/test/langChainTest.py
Labels: ✨ Feature

#62 [bug/#27] tts 버그 수정
  app/config/elevenlabs/text_to_speech_stream.py
  app/services/bubble_service.py
  app/test/anyioTest.py
Labels: 🐞 BugFix

#68 [Feat/#30] 버블 생성시 채팅방 유효성 확인, 레디스 저장 추가
  app/routers/chats.py
  app/services/bubble_service.py
Labels: ✨ Feature

#75 [feat/#34] 발췌 이미지 배경 목록 조회
  app/config/aws/s3Client.py
  app/routers/images.py
  app/services/image_service.py
Labels: ✨ Feature

#78 [Feat/#33] 랭체인으로 채팅 토큰 제한
  app/config/langChain/langChainSetting.py
  app/requirements.txt
  app/services/bubble_service.py
Labels: ✨ Feature

#83 [Feat/#35] 채팅 기능 추가 및 trimmer 일시 주석화
  app/config/langChain/langChainSetting.py
  app/services/bubble_service.py
Labels: 🐞 BugFix, ✨ Feature

#87 [feat/#38] langchain timmer 적용
  app/config/langChain/langChainSetting.py
  app/main.py
Labels: 🐞 BugFix, ✨ Feature

#91 [feat/#40] 목소리 목록 조회 character_image 추가
  app/config/aws/s3Client.py
  app/models/character.py
  app/schemas/voice.py
  app/services/voice_service.py
Labels: ✨ Feature

#103 [feat/#46] 다운로드 기능 추가
  app/models/image.py
  app/models/voice.py
  app/routers/images.py
  app/routers/voices.py
  app/services/image_service.py
  app/services/voice_service.py
Labels: ✨ Feature

#105 [feat/#45] 채팅방 별 카테고리 분석 기능 구현
  app/config/langChain/langChainSetting.py
  app/models/chat.py
  app/routers/tests.py
  app/schemas/chat.py
  app/services/bubble_service.py
  app/services/chat_service.py
  docker-compose.yml
Labels: ✨ Feature

#109 [feat/#48] 대시보드 데이터 조회 api 구현
  app/routers/characters.py
  app/schemas/character.py
  app/schemas/dashboard.py
  app/services/character_service.py
  app/services/image_service.py
  app/services/voice_service.py
Labels: ✨ Feature

#114 [feat/#44] 독한말 매운맛 기능 추가
  app/config/langChain/langChainSetting.py
  app/models/chat.py
  app/routers/chats.py
  app/schemas/bubble.py
  app/schemas/chat.py
  app/services/bubble_service.py
  app/services/chat_service.py
Labels: ✨ Feature

#123 [feat/#47] 데이터소스.yml 대시보드.yml 제이슨 파일
  app/main.py
  monitoring/grafana/dashboards/dash.json
  monitoring/grafana/dashboards/dashboards.yml
  monitoring/grafana/datasources/datasouce.yml
  monitoring/prometheus/prometheus.yml
Labels: 🐞 BugFix

#126 [feat/#55] nginx 적용
  docker-compose-deploy.yml
  nginx/nginx.conf
Labels: ⚙ Setting, ✨ Feature

#141 [main] merge 및 최신화
  docker-compose-deploy.yml
  nginx/configs/bot-block.conf
  nginx/configs/ip-block-list.conf
  nginx/configs/nginx-blue.conf
  nginx/configs/nginx-green.conf
  nginx/configs/word-block.conf
  nginx/nginx.conf
Labels: ⚙ Setting

#144 [bug/#59] 앤드포인트 수정 및 모니터링 수정
  app/routers/images.py
  app/routers/voices.py
  monitoring/elk/filebeat/filebeat.yml
  monitoring/elk/logstash/logstash.yml
  monitoring/prometheus/prometheus.yml
Labels: 🐞 BugFix

#143 [set/#61] nginx-prometheus-exporter 설정 추가
  app/main.py
  docker-compose-deploy.yml
  monitoring/prometheus/prometheus.yml
  nginx/configs/nginx-blue.conf
  nginx/configs/nginx-green.conf
  nginx/nginx.conf
Labels: ⚙ Setting

#147 [feat/#62] feat: description 추가
  app/models/character.py
  app/schemas/character.py
  app/services/character_service.py
Labels: ✨ Feature

#160 [feat/#65] 목소리 저장 시 s3 audio_url 반환하도록 변경
  app/routers/voices.py
Labels: ✨ Feature

#159 [set/#66] Timezone 서울 설정
  app/Dockerfile
  docker-compose-deploy.yml
Labels: ⚙ Setting

#166 [bug/#68] voice schema 누락 수정
  app/services/voice_service.py
Labels: 🐞 BugFix

#172 [fix/#70] audio stream 누락 문제 해결
  app/services/bubble_service.py
Labels: 🐞 BugFix

#173 [main] 최신화
  app/services/bubble_service.py
Labels: 🐞 BugFix
